### ISSUE TITLE
Not able to fire android back button

### ISSUE THREAD

**Issue by koolll** [jpntex/NavDrawer#1]
Hi , i like your widget so much. But i found that got one issue when i using this widget. I Need to back to home page when click the back button. But i am not able to fire the back button. Did you gt any solution?

**Comment by jpntex** [comment]
Hi @koolll, i've added some methods to the widget to help you with that, you can now use:

``` javascript
function backHome(e) {
    e.cancelBubble = true;

    var view = Alloy.createController('home').getView();
    $.navDrawer.changeView(view);
}

if (OS_ANDROID) {
    $.navDrawer.on('android:back', backHome);
}
```
