### ISSUE TITLE
Can't open another view with same controller?

### ISSUE THREAD

**Issue by ksouthworth** [jpntex/NavDrawer#2]
I'm trying to open another view for the same controller but the second view is not being shown/swapped in.

For example:

```
$.navDrawer.changeView( Alloy.createController('detail', { id: 5 }).getView() );

// THIS VIEW IS NEVER DISPLAYED
$.navDrawer.changeView( Alloy.createController('detail', { id: 12 }).getView() );
```

I think it's due to this line in `changeView()` line `291`

```
if (view.id !== currentView.id) {
}
```

If I comment this line then it works as expected.  Is there any danger to leaving this line commented-out?

**Comment by jpntex** [comment]
Hi @ksouthworth. The method `changeView()` only changes views when the next view is different from the previous. When you try to change the view **detail** for the same view **detail** the change will not happen, even if the view arguments are different.

For this specific problem I would suggest, if you're not trying to change views but only view's content, to implement a method in **detail**'s controller to make those content changes.

The only problem in leaving that line commented-out is the unnecessary work of removing the entire view just to add it again.

**Comment by ksouthworth** [comment]
Good suggestion, thank you
